### PR TITLE
Fix for #488, non-existent module files

### LINKED ISSUE #488: Cannot attach to processes with DLLs without physical files
On Windows system running **SentinelOne** [https://en.wikipedia.org/wiki/SentinelOne], snoop is unable to attach to the WPF process.

SentinelOne has a kernel mode driver that as part of its virus scanner and protection package injects two DLL's into the memory of every process, namely **ntd1l.dll** and **kern3l.dll** (yes, the names look very suspecious, like a mallware). Those DLL's are not found on the file system and have no files, even if the module entry in the process lists them as having one.

Snoop tries to get the file version of those non-existent DLL files and crashes while loading the injector. The following is shown in the debug logs:
```
[Injector Output] C:\Windows\SYSTEM32\ntd1l.dll
[Injector Output] System.IO.FileNotFoundException: C:\Windows\SYSTEM32\ntd1l.dll
[Injector Output]    at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
[Injector Output]    at Snoop.InjectorLauncher.ProcessWrapper.GetSupportedTargetFramework(Process process) in C:\Dev\Reference\snoopwpf\Snoop.InjectorLauncher\ProcessWrapper.cs:line 95
[Injector Output]    at Snoop.InjectorLauncher.ProcessWrapper..ctor(Process process, IntPtr windowHandle) in C:\Dev\Reference\snoopwpf\Snoop.InjectorLauncher\ProcessWrapper.cs:line 18
[Injector Output]    at Snoop.InjectorLauncher.ProcessWrapper.From(Int32 processId, IntPtr windowHandle) in C:\Dev\Reference\snoopwpf\Snoop.InjectorLauncher\ProcessWrapper.cs:line 39
```

This only happens in snoop debug builds.

```text
- Snoop: 6.0.0
- Windows 10.0.19045.6216
- .NET 10.0.100
```

### PR DESCRIPTION
**Pull request by todor-dk**
Fixes #488

### CODE REVIEW

File: Snoop.InjectorLauncher/ProcessWrapper.cs [hunk 1]
```diff
@@ -92,9 +92,20 @@ private static string GetSupportedTargetFramework(Process process)
         {
 #if DEBUG
             Injector.LogMessage(module.szExePath);
-            var fileVersionInfo = FileVersionInfo.GetVersionInfo(module.szExePath);
-            Injector.LogMessage($"File: {fileVersionInfo.FileVersion}");
-            Injector.LogMessage($"Prod: {fileVersionInfo.ProductVersion}");
+            try
```
Comment (batzen) [inline Snoop.InjectorLauncher/ProcessWrapper.cs:95]: It would be better to just check if the file exists instead of catching an exception.

**Review by batzen — CHANGES_REQUESTED** [review]

File: Snoop.InjectorLauncher/ProcessWrapper.cs [hunk 2]
```diff
@@ -1,4 +1,4 @@
-namespace Snoop.InjectorLauncher;
+﻿namespace Snoop.InjectorLauncher;
```
Comment (batzen) [inline Snoop.InjectorLauncher/ProcessWrapper.cs]: Why did you change this line/the file header?

**Review by batzen — CHANGES_REQUESTED** [review]

File: Snoop.InjectorLauncher/ProcessWrapper.cs (hunk 2 above)
Comment (todor-dk) [reply Snoop.InjectorLauncher/ProcessWrapper.cs]: I guess this was a mistake. Probably the IDE removed white-spaces.

File: Snoop.InjectorLauncher/ProcessWrapper.cs (hunk 1 above)
Comment (todor-dk) [reply Snoop.InjectorLauncher/ProcessWrapper.cs:95]: Yes, I thought of that. But if the file is inaccessible, broken or similar, we have the same problem. Do you want me to change it to FileExists and drop the try-catch?

Comment (batzen) [reply Snoop.InjectorLauncher/ProcessWrapper.cs:95]: Uh. Yeah... Then just ignore my comment and keep the simple try/catch. It's only done in debug mode anyways.

File: Snoop.InjectorLauncher/ProcessWrapper.cs (hunk 2 above)
Comment (batzen) [reply Snoop.InjectorLauncher/ProcessWrapper.cs]: Are you going to resolve this?

Comment (batzen) [reply Snoop.InjectorLauncher/ProcessWrapper.cs]: Huhu? @todor-dk

**Comment by todor-dk** [comment]
Hi Sebastian. I was gone January and sick most of February. I will look at this in the next few days.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by batzen** [comment]
Thanks for contributing!
